version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
        test: ["CMD", "rabbitmqctl", "status"]
        interval: 30s
        timeout: 10s
        retries: 5
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
  compliance:
    build:
      context: ./compliance
      dockerfile: Dockerfile
    container_name: compliance
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq