services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
        test: ["CMD", "rabbitmqctl", "status"]
        interval: 30s
        timeout: 10s
        retries: 5
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - redis
    environment:
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
      
  logistics:
    build:
      context: ./logistics
      dockerfile: Dockerfile
    container_name: logistics
    depends_on:
      - rabbitmq
      - redis
    environment:
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
      
  logistics-results:
    build:
      context: ./logistics
      dockerfile: Dockerfile.results
    container_name: logistics-results
    depends_on:
      - rabbitmq
      - redis
    environment:
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
  compliance:
    build:
      context: ./compliance
      dockerfile: Dockerfile
    container_name: compliance
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
  compliance-soap:
    build:
      context: ./compliance
      dockerfile: Dockerfile.soap
    container_name: compliance-soap
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis